name: CI Pipeline

on:
  push:
    paths:
      - 'app/**'
      - 'tests/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'Makefile'
  workflow_dispatch: # For manual trigger

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: make build

      - name: Run tests
        run: make test

      - name: Perform linting
        run: make lint

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: make docker-login

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: make docker-build-push
